// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Data;

#nullable disable

namespace TMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723161431_MakeCategoryNameUniquePerUser")]
    partial class MakeCategoryNameUniquePerUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TMS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#0d6efd",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Software development tasks",
                            Name = "Development",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#6f42c1",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UI/UX design tasks",
                            Name = "Design",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#198754",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Marketing and promotion tasks",
                            Name = "Marketing",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#fd7e14",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Meetings and coordination",
                            Name = "Meeting",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research and analysis tasks",
                            Name = "Research",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TMS.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DueDate");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initialize the ASP.NET Core MVC project with proper folder structure",
                            DueDate = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Set up project structure",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create EF Core models and configure relationships",
                            DueDate = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 2,
                            Title = "Design database schema",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build an attractive dashboard with task statistics",
                            DueDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Status = 1,
                            Title = "Create dashboard UI",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full CRUD operations for task management",
                            DueDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 1,
                            Title = "Implement task CRUD",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cover controllers and services with unit tests",
                            DueDate = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Write unit tests",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan and execute Q3 marketing campaign",
                            DueDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 0,
                            Title = "Marketing campaign Q3",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan next sprint with the team",
                            DueDate = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Title = "Sprint planning meeting",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research competitors and compile report",
                            DueDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Title = "Competitor analysis",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://pub-a981f7fafe3c46e98d60519aae806cf8.r2.dev/Avatar/Male/Number_21_b9m4ba_elzprp.png",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed@tms.com",
                            Name = "Ahmed Hamada",
                            Password = "$2a$11$im1itOCIomo1FryxxRewfOz9dCxfJ6eFBTpoOLiTK/ZAJvYtkUExm"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://pub-a981f7fafe3c46e98d60519aae806cf8.r2.dev/Avatar/Female/Number_47_ssmlmw_zlydth.png",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara@tms.com",
                            Name = "Sara Ali",
                            Password = "$2a$11$im1itOCIomo1FryxxRewfOz9dCxfJ6eFBTpoOLiTK/ZAJvYtkUExm"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://pub-a981f7fafe3c46e98d60519aae806cf8.r2.dev/Avatar/Male/Number_21_b9m4ba_elzprp.png",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohamed@tms.com",
                            Name = "Mohamed Hassan",
                            Password = "$2a$11$im1itOCIomo1FryxxRewfOz9dCxfJ6eFBTpoOLiTK/ZAJvYtkUExm"
                        });
                });

            modelBuilder.Entity("TMS.Models.Category", b =>
                {
                    b.HasOne("TMS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMS.Models.TaskItem", b =>
                {
                    b.HasOne("TMS.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TMS.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMS.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TMS.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
